# Configuration of Hugo
# Guide: https://sourcethemes.com/academic/docs/get-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Natalia Morandeira"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://nmorandeira.netlify.app/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = ""

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "hugo-academic"

# Get last modified date for content from Git?
enableGitInfo = false

## Publication date
[frontmatter]
date = ["publishDate", ":filename", "date", ":fileModTime"]
lastmod = ["lastmod", ":fileModTime", "date", "publishDate"]
publishDate = ["publishDate", ":filename", "date", ":fileModTime"]

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "es"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.
[permalinks]
  authors = "/author/:slug/"
  tags = "/tag/:slug/"
  categories = "/category/:slug/"
  publication_types = "/publication-type/:slug/"

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

# Related content.
[related]
  threshold = 80.0
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "title"
    weight = 60.0

  [[related.indices]]
    name = "summary"
    weight = 50.0

  [[related.indices]]
    name = "tags"
    weight = 80.0

  [[related.indices]]
    name = "categories"
    weight = 70.0

  [[related.indices]]
    name = "authors"
    weight = 20.0
    

